// Copyright © 2023 Meroxa, Inc. & Yalantis
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package iterator

const (
	queryGetMaxValue = `SELECT max(%s) FROM %s`

	queryCreateTable = `
		CREATE TABLE %s (
		    %s,
		    %s VARCHAR(10),
		    %s INT GENERATED BY DEFAULT AS IDENTITY (CYCLE)
		)
	`
	queryIfTableExist = `SELECT count(*) AS count FROM TABLES WHERE TABLE_NAME = $1`

	queryAddInsertTrigger = `
		 CREATE OR REPLACE TRIGGER %s                  
		 AFTER INSERT ON %s                                   
		 REFERENCING NEW ROW nw, OLD ROW rw          
		 FOR EACH ROW                                             
		 BEGIN                                                    
		  INSERT INTO %s (%s) VALUES(%s, 'INSERT'); 
		 END
	`
	queryUpdateTrigger = `
		 CREATE OR REPLACE TRIGGER %s                  
		 AFTER UPDATE ON %s                                   
		 REFERENCING NEW ROW nw, OLD ROW rw          
		 FOR EACH ROW                                             
		 BEGIN                                                    
		  INSERT INTO %s (%s) VALUES(%s, 'UPDATE'); 
		 END
	`
	queryDeleteTrigger = `
		 CREATE OR REPLACE TRIGGER %s                  
		 AFTER DELETE ON %s                                   
		 REFERENCING NEW ROW nw, OLD ROW rw          
		 FOR EACH ROW                                             
		 BEGIN                                                    
		  INSERT INTO %s (%s) VALUES(%s, 'DELETE'); 
		 END
	`
)
