// Code generated by paramgen. DO NOT EDIT.
// Source: github.com/conduitio/conduit-connector-sdk/cmd/paramgen

package source

import (
	sdk "github.com/conduitio/conduit-connector-sdk"
)

func (Config) Parameters() map[string]sdk.Parameter {
	return map[string]sdk.Parameter{
		"auth.clientCertFilePath": {
			Default:     "",
			Description: "clientCertFilePath path to file, parameter for X509 auth.",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{},
		},
		"auth.clientKeyFilePath": {
			Default:     "",
			Description: "clientKeyFilePath path to file, parameter for X509 auth.",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{},
		},
		"auth.dsn": {
			Default:     "",
			Description: "dsn connection to SAP HANA database.",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{},
		},
		"auth.host": {
			Default:     "",
			Description: "host link to db.",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{},
		},
		"auth.mechanism": {
			Default:     "DSN",
			Description: "mechanism type of auth. Valid types: DSN, Basic, JWT, X509.",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{
				sdk.ValidationInclusion{List: []string{"DSN", "Basic", "JWT", "X509"}},
			},
		},
		"auth.password": {
			Default:     "",
			Description: "password parameter for basic auth.",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{},
		},
		"auth.token": {
			Default:     "",
			Description: "token parameter for JWT auth.",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{},
		},
		"auth.username": {
			Default:     "",
			Description: "username parameter for basic auth.",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{},
		},
		"batchSize": {
			Default:     "1000",
			Description: "batchSize is a size of rows batch.",
			Type:        sdk.ParameterTypeInt,
			Validations: []sdk.Validation{
				sdk.ValidationGreaterThan{Value: 0},
				sdk.ValidationLessThan{Value: 10001},
			},
		},
		"orderingColumn": {
			Default:     "",
			Description: "orderingColumn is a name of a column that the connector will use for ordering rows.",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{
				sdk.ValidationRequired{},
			},
		},
		"primaryKeys": {
			Default:     "",
			Description: "primaryKeys list of column names should use for their `Key` fields.",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{},
		},
		"snapshot": {
			Default:     "true",
			Description: "snapshot whether or not the plugin will take a snapshot of the entire table before starting cdc.",
			Type:        sdk.ParameterTypeBool,
			Validations: []sdk.Validation{},
		},
		"table": {
			Default:     "",
			Description: "table is a name of the table that the connector should write to or read from.",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{
				sdk.ValidationRequired{},
			},
		},
	}
}
